### ISSUE TITLE
👏 如何去除 button 的边框

### ISSUE THREAD

**Issue by heycqing** [heycqing/Community-miniprogram#3]
## 如何去除 button 的边框

> 现象：

我在做一个 **圆形按钮** 的时候，出现了边框，我要把它去除。<br>
我就按照 ` css ` 那套来写了如下代码：
```css
button{
  border:none;
  outline:none;
}
```
**结果是没有用**

#### 如何解决：

加入如下代码：
```css
button:after{
  outline:none;
}
```
